# Generated by Django 4.2.7 on 2023-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='bin',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
